services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  simulator:
    build: ./simulator
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: traffic_user
      POSTGRES_PASSWORD: traffic_pass
      POSTGRES_DB: traffic_db
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
